### ISSUE TITLE
socket.findOnNetwork();

### ISSUE THREAD

**Issue by exdirectory** [tavalin/s20-sdk#14]
This method no longer exists (see your example), is this no longer required?

Seems to work without it, but see my other issue for repeating 3 times.

**Comment by tavalin** [comment]
Traveling at the moment so will look into it when I return end of next week.

**Comment by tavalin** [comment]
Just a quick note, this was changed to find() rather than findOnNetwork().  I'll update the docs but you shouldn't need to call it if you've done a global discovery.  The purpose is to ascertain the IP for the device, but if the library doesn't already know it's IP it will send a broadcast instead (which the device will response to).

Once I've updated the doc I'll close this issue.

**Comment by exdirectory** [comment]
Understood, will check my code, but have closed anyway.
